Review.destroy_all

weather = SfxPack.find_by("title ilike ?", "%weather%")
underground = SfxPack.find_by("title ilike ?", "%underground%")
outdoor = SfxPack.find_by("title ilike ?", "%outdoor%")
natural = SfxPack.find_by("title ilike ?", "%natural%")
monster = SfxPack.find_by("title ilike ?", "%monster%")
guns = SfxPack.find_by("title ilike ?", "%guns%")
ghost = SfxPack.find_by("title ilike ?", "%ghost%")
free = SfxPack.find_by("title ilike ?", "%free%")

user = User.find_by_email("unity_publisher@gmail.com")

Review.new(sfx_pack: monster, user: user, title: "Nice punch collection", content: "I like the collection very much. Great variety and you can use the sounds for other combat stuff as well. For example, you can add a sword impact sound to one of the more human punch hit sounds and use that for great sword smashing. What I don’t like so much is the big bassy thump sound that was added to many of the punch sfx (he described in the really nice video about how those sounds were created). It’s just a bit too much. I got that improved by adding a subtle high-pass filter, so not a big deal.", author: "Anonymous", rating: 4)
Review.create(sfx_pack: underground, user: user, title: "This is one of my favorite assets", content: "The effort the creator puts in his work is noticeable across all his assets and this one is no exception. I just wish this asset had all the elements in separate layers; this would stupendously increase the flexibility of the asset. Regardless, I really like it.", author: "Anonymous", rating: 5)
Review.create(sfx_pack: monster, user: user, title: "Highly recommended!", content: "I bought this as part of a humble bundle. It includes a large amount of quality audio clips, and the developer was very helpful and accommodating when I contacted him. Would definitely purchase more like this.", author: "Anonymous", rating: 5)
Review.create(sfx_pack: outdoor, user: user, title: "Great", content: "Top quality sound effects!", author: "Anonymous", rating: 4)
Review.create(sfx_pack: outdoor, user: user, title: "This is a nice asset.", content: "The quality is good and I do love the fact that it comes with separate layers. My only problem with the asset is that it doesn’t have any real calm forest ambience. The ones present are too “windy” and/or too major. This is a bummer since it was the main reason I got this asset. I hope the author updates this asset with some calm forest ambience - free from wildlife, to make scenes complete in my eyes. What I’m really looking is: - An ambience forest, with practically no wind, just a soft atmosphere without any wild life. I’m willing to update my review should the developer seeks to work on this. Regardless, I recommend this asset as is. [EDIT] Oliver, I really appreciate your response. On my book, creators that listen to feedback, or even a simple review and reply, I would just like to provide some additional feedback. The reason why I was searching for fond of calm ambiences, is they will serve as a foundation on which other layers can be added (can be as sound fx layers), or the developer can end add layers on top of that base atmosphere to create full dynamic soundscapes. I would encourage you to keep ambiences somewhat “simple” in terms of what’s included, so the developers will know what’s included in the audio and what goes - these should be on sound layers. The reason for this is that, these sounds will reflect on what the player sees. If you start your scene with a bird, but the scene doesn’t reflect that visually, it will be off putting. That’s why I’m not a fan of pre-made sound libraries with basically just layers. This will give me the flexibility to create soundscapes for existing environments. Depending on the type of scene, people would just be happy with fully assembled atmospheres out of the layers and others, requiring more flexibility, hence me saluting you for having both in your asset. The sound is well done. It is library I will contact you via e-mail as I have some ideas for sound assets. If you are interested :)", author: "Anonymous", rating: 5)
Review.create(sfx_pack: monster, user: user, title: "Very comprehensive", content: "There is so much content that is just a steal for 20 bucks.", author: "Anonymous", rating: 5)
Review.create(sfx_pack: monster, user: user, title: "Very high quality SFX", content: "At first, the author had done difficulties with preparing the asset for use in real projects. It was noticeable that the author is a master of his craft, but not familiar with game development. So I contacted him and told him how sounds are usually used in games. The author was open to feedback, so all problems were quickly resolved. Therefore, I recommend this asset for purchase. And if you have any difficulties, just write to the author, he replies very quickly.", author: "Anonymous", rating: 5)
Review.create(sfx_pack: monster, user: user, title: "Monster Sound Pack EDIT:", content: "Changed to 5 stars because the new update adds a huge amount of use and corrected the issues! A lot of the spoken voice lines are just sound bite transformers unfortunately. They heavily proceed them with multiple layering sound noises. This is partly because the pack is older where a breadth of recording talent wasn’t available to people through internet services like fiverr or freelancers. A great example of how it’s aged is one track titled 'Chimera growl' where a robot style sound from the first transformers movie (2007) can be heard in the back and mid layers. These days, there is a heavy amount of layering, distortion and splicing of samples to help mask the origin. This was missing. Majority of this pack is above 20 seconds long. There is a heavy amount of reverb used which limits the scope in which you can use the files with. Majority of the clips are voice-centric. There is a heavy amount of voice sfx clips such as yelling, grunting and other monster talk style sfx. There is some foley work (axe dragging, walking, footsteps). This is a hard sound effect asset to use. The kind of use case would be a cutscene, character interaction voice lines, maybe a cinematic segment in deep lighting (in my opinion this would not even be the asset I store in scene timeline - this would be more so for post production).", author: "Anonymous", rating: 5)
Review.create(sfx_pack: monster, user: user, title: "Great Monster SFX after updates", content: "Bought after listening to the updates that solved most of the original problems of largely-unusable 20-second-long selections that start far into the game’s scenes. There is a huge thunder shadow voice, some monstrous yelling voices, and also a wide variety of different enemies. One of the 20-second long one is an archer but what would you like in non-aggressively seeking like a demonic fire archer with battle cries. OLD VERSION (IGNORED): Don’t get me started. It was the same sort of trouble I had with some mistakenly selected SFX in an ambient weapons training section. Some other problems still remain but are now trimmed. The majority of monster SFX are 3-4 seconds of roaring with effects for most monsters. Maybe 3-4 SFX was combined together. Inside the timeline is totally unusable in any real environment. Each one of the monster SFX was used for a fixed person within 3-4 seconds. The effect wouldn’t really match the tone of enemy weapon capture versus effects and join some sort of 'in-the-loop' update includes individual raw takes with the character voice. This update finally makes sense and improves the overall spirit of the 'monster voices'. Updates remain available for 12 months so consider waiting for more feedback before finalizing the quality for monster voices for the price tag. A lot of the other negative reviews are likely for the old version, so take that in consideration.", author: "Anonymous", rating: 5)
Review.create(sfx_pack: monster, user: user, title: "Love it", content: "Perfect fit for my RPG game, love it", author: "Anonymous", rating: 5)
Review.create(sfx_pack: monster, user: user, title: "Stunning", content: "Love the assets.", author: "Anonymous", rating: 5)
Review.create(sfx_pack: outdoor, user: user, title: "Really great but small high-quality beautiful sounds.", content: "I just wish there were more of them! Despite the lack of variety, the quality is fabulous and the background feel is one of the best I've ever worked with. Some smaller sounds and individual loops, would be easier to use, then you aren't stuck in one eventful, powerful moment that plays out over time (there were two: one sounds like an Amazonian special, another is your need to use the 'demo song' as it is). They are too eventful. You need to manually pull out the bits you want to extract to get what you want for a typical game. Great work!", author: "Anonymous", rating: 5)

Review.all.each { |review| review.accepted! }
puts "There are #{Review.count} reviews created"
