// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationModalController from "./application_modal_controller"
application.register("application-modal", ApplicationModalController)

import BannerFormController from "./banner_form_controller"
application.register("banner-form", BannerFormController)

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import CollectionCheckoutModalController from "./collection_checkout_modal_controller"
application.register("collection-checkout-modal", CollectionCheckoutModalController)

import CollectionNameController from "./collection_name_controller"
application.register("collection-name", CollectionNameController)

import DatePickerDesignerSalesController from "./date_picker_designer_sales_controller"
application.register("date-picker-designer-sales", DatePickerDesignerSalesController)

import DeleteJobController from "./delete_job_controller"
application.register("delete-job", DeleteJobController)

import DesignerPackFilterController from "./designer_pack_filter_controller"
application.register("designer-pack-filter", DesignerPackFilterController)

import DesignerSubmissionFormController from "./designer_submission_form_controller"
application.register("designer-submission-form", DesignerSubmissionFormController)

import DisplayCalendarDesignerSalesController from "./display_calendar_designer_sales_controller"
application.register("display-calendar-designer-sales", DisplayCalendarDesignerSalesController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HorizontalScrollController from "./horizontal_scroll_controller"
application.register("horizontal-scroll", HorizontalScrollController)

import IconToggleController from "./icon_toggle_controller"
application.register("icon-toggle", IconToggleController)

import ItemsSoldController from "./items_sold_controller"
application.register("items-sold", ItemsSoldController)

import OpenSubscribeModalController from "./open_subscribe_modal_controller"
application.register("open-subscribe-modal", OpenSubscribeModalController)

import OrderByController from "./order_by_controller"
application.register("order-by", OrderByController)

import PhotoUploadController from "./photo_upload_controller"
application.register("photo-upload", PhotoUploadController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import ShowReviewController from "./show_review_controller"
application.register("show-review", ShowReviewController)

import SingleMobileDropdownController from "./single_mobile_dropdown_controller"
application.register("single-mobile-dropdown", SingleMobileDropdownController)

import SubmissionImagePreviewController from "./submission_image_preview_controller"
application.register("submission-image-preview", SubmissionImagePreviewController)

import SubmissionModalController from "./submission_modal_controller"
application.register("submission-modal", SubmissionModalController)

import SubmissionPdfPreviewController from "./submission_pdf_preview_controller"
application.register("submission-pdf-preview", SubmissionPdfPreviewController)

import TemplateFormController from "./template_form_controller"
application.register("template-form", TemplateFormController)

import TheQuestModalController from "./the_quest_modal_controller"
application.register("the-quest-modal", TheQuestModalController)

import TomSelectPackSubmissionCategoryController from "./tom_select_pack_submission_category_controller"
application.register("tom-select-pack-submission-category", TomSelectPackSubmissionCategoryController)

import TomSelectPackSubmissionTagsController from "./tom_select_pack_submission_tags_controller"
application.register("tom-select-pack-submission-tags", TomSelectPackSubmissionTagsController)

import TooltipMobileController from "./tooltip_mobile_controller"
application.register("tooltip-mobile", TooltipMobileController)

import UnwrapCartController from "./unwrap_cart_controller"
application.register("unwrap-cart", UnwrapCartController)

import UpdateInfoController from "./update_info_controller"
application.register("update-info", UpdateInfoController)

import VideoModalController from "./video_modal_controller"
application.register("video-modal", VideoModalController)
